name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 20.70.211.17 >> ~/.ssh/known_hosts

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, bcmath, redis

    - name: Install Dependencies
      run: |
        composer install
        cp .env.example .env
        php artisan key:generate

    - name: Deploy Application
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.70.211.17 <<EOF
        cd /var/www/laravel-todolist-api
        sudo su
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        sudo systemctl restart php8.3-fpm
        sudo systemctl restart nginx
        EOF
