name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, bcmath, redis

    - name: Install Dependencies
      run: |
        composer install
        cp .env.example .env
        php artisan key:generate

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.70.208.207 <<EOF
          cd /var/www/laravel-todolist-api
          git pull origin main
          composer install
          php artisan migrate --force
          php artisan optimize
        EOF
