name: SSH into Vagrant VM and Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  ssh-into-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into Vagrant VM, create directory, and run Ansible playbook
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.70.208.207 "
        cd ansible &&
        ansible-playbook -i inventory.ini main.yaml
        "
